"""empty message

Revision ID: 1be794b809f2
Revises: 58ec27c2186b
Create Date: 2025-07-17 06:53:30.580727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1be794b809f2'
down_revision = '58ec27c2186b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_url', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('action_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('contractor_id', sa.Integer(), nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'contractors', ['contractor_id'], ['id'])
        batch_op.create_foreign_key(None, 'actions', ['action_id'], ['id'])
        batch_op.drop_column('file')

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint('expenses_document_id_fkey', type_='foreignkey')
        batch_op.drop_column('document_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('expenses_document_id_fkey', 'documents', ['document_id'], ['id'])

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('description',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=250),
               existing_nullable=False)
        batch_op.drop_column('contractor_id')
        batch_op.drop_column('action_id')
        batch_op.drop_column('file_url')

    # ### end Alembic commands ###
