"""empty message

Revision ID: 45d5f6c086d2
Revises: ecf367431de8
Create Date: 2025-06-24 15:47:35.821071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45d5f6c086d2'
down_revision = 'ecf367431de8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assoc_tenants_apartments_contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('renta', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assoc_tenants_apartments_contracts', schema=None) as batch_op:
        batch_op.drop_column('renta')

    # ### end Alembic commands ###
