"""empty message

Revision ID: 4748c60cce4b
Revises: 10dfb9cf7bc8
Create Date: 2025-07-18 14:32:59.493315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4748c60cce4b'
down_revision = '10dfb9cf7bc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.drop_column('bill_image')
        batch_op.drop_column('bill_amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bill_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('bill_image', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
