"""empty message

Revision ID: 58ec27c2186b
Revises: c9d94f0895a2
Create Date: 2025-07-16 06:17:47.253967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58ec27c2186b'
down_revision = 'c9d94f0895a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('iva_percent', sa.Numeric(precision=5, scale=2), nullable=False))
        batch_op.add_column(sa.Column('withholding_percent', sa.Numeric(precision=5, scale=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_column('withholding_percent')
        batch_op.drop_column('iva_percent')

    # ### end Alembic commands ###
