"""empty message

Revision ID: 5fd3daec4f12
Revises: f21bca03ae67
Create Date: 2025-07-02 16:27:07.157217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fd3daec4f12'
down_revision = 'f21bca03ae67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=255), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
