"""empty message

Revision ID: 71091997b37d
Revises: b9d8ca3dff36
Create Date: 2025-07-17 18:29:25.530973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71091997b37d'
down_revision = 'b9d8ca3dff36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('action_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'actions', ['action_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('action_id')

    # ### end Alembic commands ###
