"""empty message

Revision ID: 85d2435f60d2
Revises: 2ea6c0138bca
Create Date: 2025-07-12 15:34:09.072122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85d2435f60d2'
down_revision = '2ea6c0138bca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apartments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provincia', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apartments', schema=None) as batch_op:
        batch_op.drop_column('provincia')

    # ### end Alembic commands ###
