"""empty message

Revision ID: a01252d7ee34
Revises: c96f4e2281b9
Create Date: 2025-08-16 09:33:04.572942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a01252d7ee34'
down_revision = 'c96f4e2281b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_owner_property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
        batch_op.create_index('ix_one_active_admin_per_owner', ['owner_id'], unique=True, postgresql_where=sa.text('active = true'))
        batch_op.create_unique_constraint('uq_admin_owner', ['admin_id', 'owner_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_owner_property', schema=None) as batch_op:
        batch_op.drop_constraint('uq_admin_owner', type_='unique')
        batch_op.drop_index('ix_one_active_admin_per_owner', postgresql_where=sa.text('active = true'))
        batch_op.drop_column('active')

    # ### end Alembic commands ###
