"""empty message

Revision ID: bbe0edacdfcf
Revises: bfeef01200eb
Create Date: 2025-06-03 16:07:52.760926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbe0edacdfcf'
down_revision = 'bfeef01200eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assoc_tenants_apartments_contracts', schema=None) as batch_op:
        batch_op.alter_column('apartment_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assoc_tenants_apartments_contracts', schema=None) as batch_op:
        batch_op.alter_column('apartment_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
