"""empty message

Revision ID: c9d94f0895a2
Revises: 5c4e5b828af2
Create Date: 2025-07-15 15:32:57.400274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9d94f0895a2'
down_revision = '5c4e5b828af2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tax_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('withholdings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('assoc_tenants_apartments_contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tax_percentage_applied', sa.Numeric(precision=5, scale=2), nullable=False))
        batch_op.add_column(sa.Column('withholding_percentage_applied', sa.Numeric(precision=5, scale=2), nullable=False))
        batch_op.add_column(sa.Column('tax_type_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('withholding_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'tax_types', ['tax_type_id'], ['id'])
        batch_op.create_foreign_key(None, 'withholdings', ['withholding_id'], ['id'])

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tax_type_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('withholding_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'withholdings', ['withholding_id'], ['id'])
        batch_op.create_foreign_key(None, 'tax_types', ['tax_type_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('withholding_id')
        batch_op.drop_column('tax_type_id')

    with op.batch_alter_table('assoc_tenants_apartments_contracts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('withholding_id')
        batch_op.drop_column('tax_type_id')
        batch_op.drop_column('withholding_percentage_applied')
        batch_op.drop_column('tax_percentage_applied')

    op.drop_table('withholdings')
    op.drop_table('tax_types')
    # ### end Alembic commands ###
