"""empty message

Revision ID: de143e658441
Revises: bc14e26b14d8
Create Date: 2025-06-10 15:40:41.513807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de143e658441'
down_revision = 'bc14e26b14d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.alter_column('bill_amount',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('bill_image',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('apartments', schema=None) as batch_op:
        batch_op.alter_column('postal_code',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=30),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apartments', schema=None) as batch_op:
        batch_op.alter_column('postal_code',
               existing_type=sa.String(length=30),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.alter_column('bill_image',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('bill_amount',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
